on:
  schedule:
    # Every Day Midnight
    - cron: '0 0 * * *'
  workflow_dispatch: {}

name: "Daily"

jobs:

  checkAsdfUpdatesNodeJs:
    name: "ASDF Update Node.js"

    uses: ./.github/workflows/part_asdf_update.yml
    with:
      plugin: "nodejs"

